### ISSUE TITLE
Potential to rename towards clarification

### ISSUE THREAD

**Issue by yawboakye** [rasheedmhd/oubre#1]
### [`ArrayChar`](https://github.com/Virux/oubre/blob/main/src/vga_buffer.rs#L55)
perhaps `ScreenChar` (preferred by the curriculum) may not be a great name but i don't think `ArrayChar` is either. the struct encompasses the single character we want to print to screen and what foreground & background colors to use. i'm not sure `ArrayChar` makes that clear. if anything, it gives the impression that it's a character in an array. while technically true (the buffer is a 2d array after all), it isn't semantic. it doesn't make the code read like a story.

### [`PrintToScreen`](https://github.com/Virux/oubre/blob/main/src/vga_buffer.rs#L83)
this is the screen we will be printing to. maybe it could be called `Screen` instead?

**Comment by rasheedmhd** [comment]
That is true. I had plans of renaming the `ArrayChar` along the line. I will do that and also check the `PrintToScreen` naming

**Comment by rasheedmhd** [comment]
`ArrayChar` has been renamed as `ScreenChar` and `PrintToScreen` has been renamed to `Screen`.

Thanks for making time to create this issue.
