### ISSUE TITLE
Challenge: different background color for blank screen (or blank rows)

### ISSUE THREAD

**Issue by yawboakye** [rasheedmhd/oubre#2]
at the moment, the screen defaults to a black background color. would be great if we could use a different background color for a blank screen. as we fill up the screen with text, the text could share the same background color as the screen. for example, if default background color were blue, then a text in yellow foreground color could be rendered without infringing on its legibility. it could also allow using black as the foreground color, in fact.

**Comment by rasheedmhd** [comment]
Background set to LightBlue. Fixed.
